// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/interfaces.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCreateUserUseCaseInterface is a mock of CreateUserUseCaseInterface interface.
type MockCreateUserUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserUseCaseInterfaceMockRecorder
}

// MockCreateUserUseCaseInterfaceMockRecorder is the mock recorder for MockCreateUserUseCaseInterface.
type MockCreateUserUseCaseInterfaceMockRecorder struct {
	mock *MockCreateUserUseCaseInterface
}

// NewMockCreateUserUseCaseInterface creates a new mock instance.
func NewMockCreateUserUseCaseInterface(ctrl *gomock.Controller) *MockCreateUserUseCaseInterface {
	mock := &MockCreateUserUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockCreateUserUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserUseCaseInterface) EXPECT() *MockCreateUserUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUserUseCaseInterface) Execute(ctx context.Context, input CreateUserUseCaseInputDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserUseCaseInterfaceMockRecorder) Execute(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUserUseCaseInterface)(nil).Execute), ctx, input)
}

// MockAuthUserUseCaseInterface is a mock of AuthUserUseCaseInterface interface.
type MockAuthUserUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUserUseCaseInterfaceMockRecorder
}

// MockAuthUserUseCaseInterfaceMockRecorder is the mock recorder for MockAuthUserUseCaseInterface.
type MockAuthUserUseCaseInterfaceMockRecorder struct {
	mock *MockAuthUserUseCaseInterface
}

// NewMockAuthUserUseCaseInterface creates a new mock instance.
func NewMockAuthUserUseCaseInterface(ctrl *gomock.Controller) *MockAuthUserUseCaseInterface {
	mock := &MockAuthUserUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthUserUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUserUseCaseInterface) EXPECT() *MockAuthUserUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAuthUserUseCaseInterface) Execute(ctx context.Context, input AuthUserUseCaseInputDTO) (*AuthUserUseCaseOutputDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*AuthUserUseCaseOutputDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAuthUserUseCaseInterfaceMockRecorder) Execute(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAuthUserUseCaseInterface)(nil).Execute), ctx, input)
}
